### PR TITLE
RealSR training results with demo project using pre-trained model

### PR DESCRIPTION
**Pull request by Hyunmin-jasper-Cho**
Implement #2 

# OVERVIEW OF PR: [LINK](https://github.com/Hyunmin-jasper-Cho/ImageSR)

## COMPLETED
- [x] EDSR demo project using **PRE-TRAINED** opencv model.  
- [x] Dataset generation using RealSR's **kernel estimation** method.  
- [x] Train RealSR model using above dataset.  
> In NVDIA P100 GPU, it takes up to **_6 hours 30 minutes_**.  
> It may not be able to train in personal desktop or laptop, therefore If you want to train, I recommended you to train using a colab pro(or pro+) condition.
- [x] Added sample result(DIV2K 998). 

## TODO (Future plan)
- [ ] Make a RGB dataset for EDSR/ESPCN, to train model using kernel estimation 
- [ ] Train EDSR/ESPCN model using above **NEW** dataset.
- [ ] Check if there are any improvement in the result. (Not only PSNR/SSIM, MOS, ...)

### CODE REVIEW

**Comment by Hyunmin-jasper-Cho** [comment]
> Ref this [link](https://github.com/Hyunmin-jasper-Cho/ImageSR), to overview my PL.

**Comment by chromato99** [comment]
Can you add .gitignore by referring to the link below?
https://github.com/github/gitignore/blob/main/Python.gitignore

**Comment by Hyunmin-jasper-Cho** [comment]
> Can you add .gitignore by referring to the link below? https://github.com/github/gitignore/blob/main/Python.gitignore

Thank you for your information.  

- [x] Added .gitignore to avoid to push **\__pycache__** and **.DS_Store** file.  
- [x] Deleted all of **\__pycache__** related file/folder.  

Please mention if there are any other issues in my work. 
 
Thank you.

**Review by chromato99 — COMMENTED** [review]
Thanks for the correction:)
There is one more thing I would like to comment.
As the RealSR follows the Apache 2.0 license, so it seems that the code you write must also specify the license as Apache2.0.
Can you add a license too?

https://github.com/jixiaozhong/RealSR/blob/master/LICENSE

**Comment by Hyunmin-jasper-Cho** [comment]
> Thanks for the correction:) There is one more thing I would like to comment. As the RealSR follows the Apache 2.0 license, so it seems that the code you write must also specify the license as Apache2.0. Can you add a license too?
> 
> https://github.com/jixiaozhong/RealSR/blob/master/LICENSE

Thank you for your information.  

I completely forgot to set the relevant license when creating the repository. 
If I proceed with Video SR later, I will add an appropriate license to the  VideoSR repository too.

- [x] Added license (Apache 2.0) to repository.  (You can check License update in [my repository](https://github.com/Hyunmin-jasper-Cho/ImageSR/blob/main/LICENSE). ) 

Please mention if there are any other issues in my work.

Thank you.

**Review by chromato99 — APPROVED** [review]
Thanks for the update.
LGTM 👍

**Pull request merged**
